"""preframr_playroutine: numpy tooling for sidtrace oracle output."""

from .trace import (
    CIA_IRQ,
    CPU_VECTOR,
    EVENT_DTYPE,
    RAMACCESS_DTYPE,
    SID_WRITE,
    SRC_CIA1,
    SRC_CIA2,
    VEC_IRQ,
    VEC_NMI,
    VEC_RST,
    VIC_IRQ,
    WIN_IRQ,
    WIN_NMI,
    Trace,
    decode_voices,
    load_events,
)
from .recover import (
    RecoverContext,
    StateSequence,
    analyze,
    classify_register,
    combine_lohi,
    correlate_event_reset,
    detect_table_walk,
    fit_bacc,
    segmented_bacc,
    state_sequence,
    voice_events,
)

__all__ = [
    "EVENT_DTYPE",
    "RAMACCESS_DTYPE",
    "SID_WRITE",
    "CIA_IRQ",
    "VIC_IRQ",
    "CPU_VECTOR",
    "VEC_IRQ",
    "VEC_NMI",
    "VEC_RST",
    "SRC_CIA1",
    "SRC_CIA2",
    "WIN_IRQ",
    "WIN_NMI",
    "Trace",
    "decode_voices",
    "load_events",
    "StateSequence",
    "RecoverContext",
    "state_sequence",
    "fit_bacc",
    "segmented_bacc",
    "combine_lohi",
    "detect_table_walk",
    "classify_register",
    "correlate_event_reset",
    "voice_events",
    "analyze",
]
